### ISSUE TITLE
关于部署问题

### ISSUE THREAD

**Issue by xiaonian233** [calibur-tv/Avalon#4]
特别喜欢这个项目，试着搜一下竟然搜到了，在进行yarn到最后出现
![image](https://user-images.githubusercontent.com/21072615/44448872-21703980-a61f-11e8-8092-8d5a5015c0fa.png)
Windows 10  [版本 10.0.17134.228]
npm 5.6.0
node 8.11.4
yarn 1.9.4
git version 2.18.0.windows.1

**Comment by falstack** [comment]
你执行的命令是什么？`git pull ?`, `git pull origin master`试试

**Comment by xiaonian233** [comment]
①git clone https://github.com/calibur-tv/Avalon.git

**Comment by xiaonian233** [comment]
master是这个问题，dev按流程没有问题

**Comment by falstack** [comment]
看看这个能不能解决你的问题：[There is no tracking information for the current branch](https://stackoverflow.com/questions/32056324/there-is-no-tracking-information-for-the-current-branch)

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/44459465-550d8c80-a63c-11e8-874f-95da870f41cc.png)
哥新的问题

**Comment by xiaonian233** [comment]
git status的截图
![image](https://user-images.githubusercontent.com/21072615/44459879-bd10a280-a63d-11e8-9acc-a7454ec35fee.png)

**Comment by falstack** [comment]
你可以尝试 fork 到你那边，看看能不能跑起来

**Comment by xiaonian233** [comment]
我发现是       
 package.json
 yarn.lock两个文件，如果本地文件夹存在这两个文件就会出现上图错误，但是删除后执行yarn不能运行，这两个文件又不可缺

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/44466161-2f8b7d80-a652-11e8-8fc1-03d061b912f2.png)
emm老哥我删除了一下缓存和失败的遗留重新走了一遍是这个

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/44470612-c4937400-a65c-11e8-8a3a-0fa0ab112597.png)

em我现在换成了centos环境用npm install尝试

**Comment by xiaonian233** [comment]
感谢老哥，错误弄完了，表示这个项目是可以供个人搭建的么，我想自建一个供内网的朋友用

**Comment by xiaonian233** [comment]
明白，最后个问题，现在项目已经跑起来了，但是始终是升级服务器，大概是还要修改相关文件才能正常运行，请问一下我应该修改那些文件？

**Comment by xiaonian233** [comment]
老哥， 最后个问题，现在项目已经跑起来了，但是始终是升级服务器，大概是还要修改相关文件才能正常运行，请问一下我应该修改那些文件？

falstack <notifications@github.com> 于2018年8月23日周四 上午9:20写道：

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/44506604-b9325e00-a6d9-11e8-98f9-c4aa9ee34108.png)
就是这个了，在文件表示没有找到类似数据库的东西

**Comment by xiaonian233** [comment]
直接访问127.0.0.1:3000是这样的
![image](https://user-images.githubusercontent.com/21072615/44506973-62c61f00-a6db-11e8-8cbc-2f47096061f6.png)
可以通过下面的回到首页跳转，直接访问的话会跳转/errors/500?redirect=%2F&message=Parse%20Error，作者这个不是用数据库来存储登录注册，视频之类的吗？

**Comment by falstack** [comment]
你需要自建一个后端的 server，这个项目是纯前端项目，不包换 API 部分

**Comment by xiaonian233** [comment]
作者我看到了Laputa这个是后端么

**Comment by falstack** [comment]
Yes

**Comment by xiaonian233** [comment]
emm作者这个后端也是可以给个人用的？

**Comment by falstack** [comment]
都是 GPL-2.0

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/44517521-86e52880-a6fa-11e8-9be2-f6cf90c9ef26.png)
老哥给瞅瞅看看这样算是好了么localhost/server.php

**Comment by falstack** [comment]
改成你 server run 的端口 就行了

**Comment by xiaonian233** [comment]
老哥run端口，我是直接80端口所以，直接写localhost就行么

**Comment by falstack** [comment]
可以的，`http://localhost/`

**Comment by xiaonian233** [comment]
em还是提示了：网络请求失败，请稍后再试！

**Comment by falstack** [comment]
。。。你没有自己的数据存储，当然会失败啊
