### ISSUE TITLE
新版出现的错误

### ISSUE THREAD

**Issue by xiaonian233** [calibur-tv/Avalon#5]
开发者很抱歉打扰您，以下是我在新版Avalon搭建出现错误，使用的是Avalon(master)最新分支
![image](https://user-images.githubusercontent.com/21072615/52895556-453fc100-31f7-11e9-9391-f0e265edb820.png)
后台应该是没有问题的
![image](https://user-images.githubusercontent.com/21072615/52895558-4ec92900-31f7-11e9-8fa7-afc138d524ca.png)
node,npm,yarn的版本
![image](https://user-images.githubusercontent.com/21072615/52895564-61dbf900-31f7-11e9-9319-4f9552e41297.png)
运行的命令是
①yarn
②npm run dev

**Comment by falstack** [comment]
请修改 .env.js 的 API

**Comment by xiaonian233** [comment]
谢谢
